openapi: 3.0.4
info:
  title: Task-tracker log models
  description: Log models for logging 'Task tracker' services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        project:
          $ref: '#/components/schemas/LogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    LogModel:
      title: Модель лога для микросервиса task-tracker
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestProject:
          $ref: '#/components/schemas/ProjectLog'
        requestFilter:
          $ref: '#/components/schemas/ProjectFilterLog'
        responseProject:
          $ref: '#/components/schemas/ProjectLog'
        responseProjects:
          type: array
          items:
            $ref: '#/components/schemas/ProjectLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    ProjectLog:
      title: Модель лога для объекта "проект"
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        createdBy:
          type: string

    ProjectFilterLog:
      title: Модель лога фильтра
      properties:
        searchText:
          type: string
        createdBy:
          type: string
